# Generated by Django 5.2 on 2025-05-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_post_image_alter_follow_id_alter_post_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
